language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-head

services: 
  - mysql

before_script:
  - mysql -e 'create database roles-field-test;' -uroot
  - cp spec/dbconfig.yaml.travis spec/dbconfig.yaml

script:
  - bundle exec rspec spec